
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRLIT = 48;
  public static final int GREATERTHAN = 38;
  public static final int SQUARE_OPEN = 12;
  public static final int DIVIDE = 26;
  public static final int GREATERTHANEQUAL = 40;
  public static final int CHAR = 16;
  public static final int EQUALS = 6;
  public static final int NOTEQUAL = 42;
  public static final int DECR = 36;
  public static final int INCR = 35;
  public static final int INT = 15;
  public static final int MINUS = 24;
  public static final int LESSTHANEQUAL = 39;
  public static final int AND = 43;
  public static final int NOT = 27;
  public static final int SEMICOLON = 9;
  public static final int INTLIT = 47;
  public static final int OR = 44;
  public static final int LESSTHAN = 37;
  public static final int BOOL = 18;
  public static final int COMMA = 11;
  public static final int CLASS = 2;
  public static final int PLUS = 22;
  public static final int MULTIPLY = 25;
  public static final int IF = 28;
  public static final int ID = 45;
  public static final int ROUND_OPEN = 7;
  public static final int EOF = 0;
  public static final int CURLY_OPEN = 3;
  public static final int RETURN = 34;
  public static final int PRINTLINE = 33;
  public static final int TRUE = 20;
  public static final int error = 1;
  public static final int VOID = 14;
  public static final int FLOATLIT = 49;
  public static final int ROUND_CLOSE = 8;
  public static final int CHARLIT = 46;
  public static final int COLON = 10;
  public static final int ELSE = 29;
  public static final int READ = 31;
  public static final int FINAL = 5;
  public static final int WHILE = 30;
  public static final int FLOAT = 19;
  public static final int EQUALSCHECK = 41;
  public static final int STRING = 17;
  public static final int QUESTION = 23;
  public static final int FALSE = 21;
  public static final int CURLY_CLOSE = 4;
  public static final int SQUARE_CLOSE = 13;
  public static final int PRINT = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "CURLY_OPEN",
  "CURLY_CLOSE",
  "FINAL",
  "EQUALS",
  "ROUND_OPEN",
  "ROUND_CLOSE",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "SQUARE_OPEN",
  "SQUARE_CLOSE",
  "VOID",
  "INT",
  "CHAR",
  "STRING",
  "BOOL",
  "FLOAT",
  "TRUE",
  "FALSE",
  "PLUS",
  "QUESTION",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "NOT",
  "IF",
  "ELSE",
  "WHILE",
  "READ",
  "PRINT",
  "PRINTLINE",
  "RETURN",
  "INCR",
  "DECR",
  "LESSTHAN",
  "GREATERTHAN",
  "LESSTHANEQUAL",
  "GREATERTHANEQUAL",
  "EQUALSCHECK",
  "NOTEQUAL",
  "AND",
  "OR",
  "ID",
  "CHARLIT",
  "INTLIT",
  "STRLIT",
  "FLOATLIT"
  };
}

